import { LanguageCode, Translation } from './types';

export const TRANSLATIONS: Record<LanguageCode, Translation> = {
  'pt-BR': {
    title: 'NutriGemini',
    subtitle: 'Transforme sua alimentação com o poder da Inteligência Artificial. Saiba exatamente o que você come e descubra receitas incríveis em segundos.',
    heroTitleStart: 'Nutrição Inteligente',
    heroTitleEnd: 'ao seu alcance',
    searchPlaceholder: 'O que você vai comer hoje? Ex: Tapioca com queijo...',
    searchButton: 'Revelar Segredos Nutricionais',
    loading: 'Nossa IA está analisando cada molécula e criando receitas exclusivas...',
    errorGeneric: 'Ops! O universo dos alimentos é vasto. Tente ser mais específico (ex: "Pizza de Calabresa") para uma análise precisa.',
    errorApiKey: 'Chave de API não configurada. Verifique o ambiente.',
    calories: 'Calorias',
    protein: 'Proteínas',
    carbs: 'Carboidratos',
    fat: 'Gorduras',
    fiber: 'Fibras',
    sugar: 'Açúcares',
    sodium: 'Sódio',
    servingSize: 'Porção Sugerida',
    macroDistribution: 'Raio-X dos Nutrientes',
    footer: 'Desenvolvido com a tecnologia Google Gemini AI - Sua saúde em primeiro lugar.',
    recipesTitle: 'Transforme esse Ingrediente em Obras-Primas',
    addToFavorites: 'Salvar nos Favoritos',
    removeFromFavorites: 'Remover',
    favoritesTitle: 'Seu Livro de Receitas Digital',
    noFavorites: 'Seu livro de receitas está vazio. Comece a explorar e salve suas favoritas!',
    prepTime: 'Preparo',
    close: 'Fechar',
    savedRecipes: 'Receitas Salvas',
    viewRecipe: 'Ver Modo de Preparo',
    ingredients: 'O que você vai precisar',
    instructions: 'Mão na Massa',
    servings: 'Rende',
    saved: 'Salva',
    // Feature Grid
    featureInstantTitle: 'Velocidade Supersônica',
    featureInstantDesc: 'Abandone as tabelas antigas. Obtenha análises precisas em tempo real com nossa IA de última geração.',
    featureAnyFoodTitle: 'Enciclopédia Infinita',
    featureAnyFoodDesc: 'De pratos típicos brasileiros a culinária exótica. Se é comida, nós sabemos tudo sobre ela.',
    featureDetailedTitle: 'Muito Além das Calorias',
    featureDetailedDesc: 'Descubra os segredos dos seus alimentos: macros, micronutrientes e como prepará-los de forma saudável.'
  },
  'en-US': {
    title: 'NutriGemini',
    subtitle: 'Transform your diet with the power of Artificial Intelligence. Know exactly what you eat and discover amazing recipes in seconds.',
    heroTitleStart: 'Smart Nutrition',
    heroTitleEnd: 'at your fingertips',
    searchPlaceholder: 'What are you eating today? Ex: Avocado Toast...',
    searchButton: 'Reveal Nutritional Secrets',
    loading: 'Our AI is analyzing every molecule and crafting exclusive recipes...',
    errorGeneric: 'Oops! The food universe is vast. Try being more specific (e.g., "Pepperoni Pizza") for a precise analysis.',
    errorApiKey: 'API Key not configured. Check environment.',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fats',
    fiber: 'Fiber',
    sugar: 'Sugar',
    sodium: 'Sodium',
    servingSize: 'Serving Size',
    macroDistribution: 'Nutrient X-Ray',
    footer: 'Powered by Google Gemini AI technology - Your health comes first.',
    recipesTitle: 'Turn this Ingredient into Masterpieces',
    addToFavorites: 'Save to Favorites',
    removeFromFavorites: 'Remove',
    favoritesTitle: 'Your Digital Cookbook',
    noFavorites: 'Your cookbook is empty. Start exploring and save your favorites!',
    prepTime: 'Prep',
    close: 'Close',
    savedRecipes: 'Saved Recipes',
    viewRecipe: 'View Recipe',
    ingredients: 'What you need',
    instructions: 'Method',
    servings: 'Yields',
    saved: 'Saved',
    // Feature Grid
    featureInstantTitle: 'Supersonic Speed',
    featureInstantDesc: 'Ditch the old charts. Get precise, real-time analysis with our state-of-the-art AI.',
    featureAnyFoodTitle: 'Infinite Encyclopedia',
    featureAnyFoodDesc: 'From local delicacies to exotic cuisine. If it\'s food, we know everything about it.',
    featureDetailedTitle: 'Beyond Calories',
    featureDetailedDesc: 'Unlock the secrets of your food: macros, micronutrients, and how to prepare them healthily.'
  }
};

export const MOCK_DATA = {
  foodName: "Exemplo (Mock)",
  calories: 0,
  protein: 0,
  carbs: 0,
  fat: 0,
  fiber: 0,
  sugar: 0,
  sodium: 0,
  servingSize: "100g",
  emoji: "🍎",
  recipes: []
};